### ISSUE TITLE
Use kustomize to install calico on cluster bootstrap

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/home-cluster#1922]
# Details

**Describe the solution you'd like:**

Instead of pulling in the manifest straight from the URL @anthr76 had an idea to use kustomize instead. This would also allow for swapping images to another registry.

```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://docs.projectcalico.org/archive/v3.20/manifests/tigera-operator.yaml
images:
- name: calico/kube-controllers
  newName: ghcr.io/k8s-at-home/calico/kube-controllers
```
