### ISSUE TITLE
Fix kube-controller-manager metrics on k3s 1.22.x

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/home-cluster#2378]
# Details

**What steps did you take and what happened:**

Upgraded to k3s 1.22 and noticed `kube-controller-manager` metrics stopped working

**What did you expect to happen:**

Metrics to work

**Anything else you would like to add:**

According to the upstream k8s release notes, the default port changed and now requires an authorized SA to access the metrics endpoint

![image](https://user-images.githubusercontent.com/213795/141519930-64a81c81-d503-4342-b1cb-f4e862195f4d.png)

---

```sh
curl -v -k https://127.0.0.1:10257/metrics
```

```json
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/metrics\"",
  "reason": "Forbidden",
  "details": {
    
  },
  "code": 403
}
```

**Comment by onedr0p** [comment]
This is fixed by changing the values in `kube-prometheus-stack`:

```yaml
    kubeControllerManager:
      enabled: true
      endpoints:
        - 192.168.42.10
        - 192.168.42.11
        - 192.168.42.12
      service:
        enabled: true
        port: 10257
        targetPort: 10257
      serviceMonitor:
        enabled: true
        https: true
        insecureSkipVerify: true
```

PR opened here to set these as defaults

https://github.com/prometheus-community/helm-charts/pull/1393
