### ISSUE TITLE
Renovate against ghcr.io/onedr0p

### ISSUE THREAD

**Issue by reefland** [onedr0p/home-cluster#5044]
When you have a moment, I can't get Renovate to detect your custom application versions.  But detects `exportarr` no problem.

Dependency Dashboard only shows an entry for `exportarr`:
![image](https://user-images.githubusercontent.com/16230914/227268540-b7c68eff-877d-4631-be20-21f97ef20d6f.png)

I tried various items like:
```
            repository: ghcr.io/onedr0p/lidarr-develop
            # renovate: datasource=docker depName=ghcr.io/onedr0p/lidarr-develop 
            tag: "1.1.3.2982"
```
```
            repository: ghcr.io/onedr0p/lidarr-develop
            # renovate: datasource=docker depName=ghcr.io/onedr0p/lidarr-develop
            tag: "1.1.3.2982@sha256:37dff1e762b8c7cb17dc212db95923f8969897f3f401b5f426afdb14ea069dee"
```
```
            repository: ghcr.io/onedr0p/lidarr-develop
            # renovate: depName=ghcr.io/onedr0p/lidarr-develop
            tag: "1.1.3.2982@sha256:37dff1e762b8c7cb17dc212db95923f8969897f3f401b5f426afdb14ea069dee"
```

Using the same pattern as `exportarr`:
```
            repository: ghcr.io/onedr0p/exportarr
            # renovate: datasource=docker depName=ghcr.io/onedr0p/exportarr
            tag: "v1.2.4"
```

RegEx Manager being used:
```
   {
      "description": "Process custom dependencies",
      "fileMatch": [
        "applications/.+\\.yaml$",
        "workloads/.+\\.yaml$"
      ],
      "matchStrings": [
        "datasource=(?<datasource>\\S+) depName=(?<depName>\\S+)( versioning=(?<versioning>\\S+))?\n.*?\"(?<currentValue>.*)\"\n"
      ],
      "datasourceTemplate": "{{#if datasource}}{{{datasource}}}{{else}}github-releases{{/if}}",
      "versioningTemplate": "{{#if versioning}}{{{versioning}}}{{else}}semver{{/if}}"
    },
```
---
I did try adding:
`":pinDigestsDisabled"` under `"extends"`, no difference.

---
The only partial success I could figure out is if I have it use `loose` versioning:
```
    {
      "description": "Loose versioning for non-semver packages",
      "matchDatasources": ["docker"],
      "versioning": "loose",
      "matchPackagePatterns": ["plex","lidarr"]
    }
```
It then detects the container image:
![image](https://user-images.githubusercontent.com/16230914/227269247-d747bc5c-6e63-421a-b0aa-85f7edab8e3b.png)

However, the PR created is to remove the pinned digest:
![image](https://user-images.githubusercontent.com/16230914/227269556-260dcf3e-c07a-43f4-ac57-32c694dc07ae.png)

![image](https://user-images.githubusercontent.com/16230914/227270315-2fb0bafe-623a-48c7-a659-faa974ed0b5f.png)
---

I could live without the pinned digest, but figured I'd ask before giving up.

**Comment by onedr0p** [comment]
Renovate by default can pick up those changes, you shouldn't need `# renovate: depName=ghcr.io/onedr0p/lidarr-develop` and a regexManager for them.

This is done by ...

```json
...
  "extends": [
...
    "docker:enableMajor",
...
  "flux": {
    "fileMatch": ["kubernetes/.+\\.ya?ml$"]
  },
  "helm-values": {
    "fileMatch": ["kubernetes/.+\\.ya?ml$"]
  },
  "kubernetes": {
    "fileMatch": ["kubernetes/.+\\.ya?ml$"]
  },
...
```

**Comment by reefland** [comment]
Sorry I was trying to keep it simple... these are part of ArgoCD.  I have:
```
"argocd": {
    "fileMatch": [
      "applications/.+\\.yaml$",
      "workloads/.+\\.yaml$"
    ]
  },
```

That only picks up the Helm Chart version, it does not pickup the `images` within the folded YAML.  To pick up the images I have to use that renovate hint.

For example with below, it only picks up the Helm chart version `1.3.2`, does not see the image below that.
```
  sources:
    - chart: app-template
      repoURL: https://bjw-s.github.io/helm-charts
      targetRevision: 1.3.2
      helm:
        values: |
          controller:
            # Valid options are deployment, daemonset or statefulset
            type: statefulset
            revisionHistoryLimit: 3

          image:
            repository: ghcr.io/onedr0p/lidarr-develop
            tag: "1.1.3.2982@sha256:37dff1e762b8c7cb17dc212db95923f8969897f3f401b5f426afdb14ea069dee"
            pullPolicy: IfNotPresent
```

Once I add in the `# renovate: datasource=docker depName=ghcr.io/onedr0p/lidarr-develop` then renovate usually picks it up.  For unknown reason, its not working on these containers but does work on `ghcr.io/onedr0p/exportarr`.

**Comment by reefland** [comment]
Thank again for taking the time to respond.  I moved the values out into its own file within ArgoCD such as:
```
  sources:
    - repoURL: https://bjw-s.github.io/helm-charts
      chart: app-template
      targetRevision: 1.3.2
      helm:
        valueFiles:
          - $values/workloads/lidarr/values.yaml
    - repoURL: 'https://github.com/reefland/k3s-argocd.git'
      targetRevision: HEAD
      ref: values
```

Within the `values.yaml` renovate hint is not needed...
```
# https://github.com/onedr0p/containers/pkgs/container/lidarr-develop
image:
  repository: ghcr.io/onedr0p/lidarr-develop
  tag: "1.1.3.2982@sha256:37dff1e762b8c7cb17dc212db95923f8969897f3f401b5f426afdb14ea069dee"
  pullPolicy: IfNotPresent
```

Dashboard shows it correctly with digest:
![image](https://user-images.githubusercontent.com/16230914/227591852-3cc20d28-d090-4c22-b33a-51dfb3cf3480.png)

I can use this pattern for digests.
