### ISSUE TITLE
Migrate config volumes to existingClaim on HelmReleases

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/home-cluster#645]
# Details

**Describe the solution you'd like:**

Using `existingClaims` will make it so when the HelmRelease is somehow uninstalled it won't take the PVC with it. Ideally defining the PVC in code like:

```yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: rook-ceph.rbd.csi.ceph.com
  labels:
    app.kubernetes.io/instance: radarr
    app.kubernetes.io/name: radarr
  name: radarr-config
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  storageClassName: rook-ceph-block
```
